export type Language = 'de' | 'en';

export const TRANSLATIONS = {
    de: {
        common: {
            score: "Punkte",
            loading: "Laden...",
            error: "Fehler",
            retry: "Nochmal versuchen (du Pechvogel)",
            done: "FERTIG",
            back: "ZURÜCK",
            pause: "PAUSE",
            continue: "WEITER",
            exit: "BEENDEN",
            saving: "WIRD GESPEICHERT...",
            submit: "EINTRAGEN",
            cancel: "ABBRECHEN",
        },
        menu: {
            title: "Fröhliche Spiele",
            grinchTitle: "Grummelige Spiele",
            finaleBadge: "FINALE",
            settings: "EINSTELLUNGEN",
            play: "SPIELEN",
            info: "INFO",
            snowballTitle: "Schneeball-Jagd",
            snowballDesc: "Tippe auf Geschenke und Sterne, um Punkte zu sammeln. Vermeide die Kohle, außer du warst unartig! Nutze Eis für einen Freeze oder Uhren für mehr Zeit.",
            giftTitle: "Geschenke Weitwurf",
            giftDesc: "Tippe, um Geschenke abzuwerfen. Ziele genau in die Schornsteine! Achte auf Hindernisse wie Flugzeuge und Wolken - Santa hat keine Haftpflicht!",
            runnerTitle: "Rentier Rennen",
            runnerDesc: "Renne endlos durch die verschneite Landschaft! Tippe zum Springen, wische nach unten zum Ducken. Weiche Hindernissen aus und sammle Punkte!",
            expired: "ABGELAUFEN",
            githubHelp: "Hilf mit, dieses Spiel zu verbessern!",
            githubVisit: "Besuche GitHub:",
        },
        settings: {
            title: "Einstellungen",
            duration: "Spieldauer:",
            sound: "Sound Effekte:",
            soundOn: "An",
            soundOff: "Aus",
            theme: "Erscheinungsbild:",
            themeClassic: "Klassisch",
            themeGrinch: "Grinch-Modus",
            min: "Min",
            sec: "Sek",
        },
        game: {
            newHighScore: "NEUER HIGHSCORE!",
            yourScore: "Dein Score",
            enterName: "NAME EINGEBEN",
            finished: "FERTIG!",
            jokeTitle: "Weihnachtswitz:",
            toMenu: "ZUM HAUPTMENÜ",
            noScores: "Noch keine Scores - sei der Erste!",
            leaderboard: "Bestenliste",
            thanks: "Danke für deine Hilfe, Santa! Ohne dich wären die Kinder leer ausgegangen!",
            freeze_text: "FREEZE!",
            poof: "POOF!",
            perfect: "PERFEKT",
            miss: "Daneben",
            playableUntil: "Spielbar bis 01.01.2026",
            gameEnded: "Spiel beendet",
            gameEndedTitle: "Ho ho ho... und Tschüss!",
            gameEndedMessage: "Die Santa Games sind offiziell vorbei! Danke an alle mutigen Spieler, die Santas Geschenke gerettet haben. Die Rentiere sind erschöpft, die Elfen im Urlaub und der Schlitten in der Werkstatt. Ob wir nächstes Jahr wieder zurückkommen? Wer weiß... vielleicht, wenn ihr brav wart! 🎅✨",
            player: "Spieler",
            players: "Spieler",
            eternalGlory: "Ewiger Ruhm erwartet die Champions!",
            runner: {
                tapToJump: "TIPPE ZUM SPRINGEN",
                swipeDown: "WISCH NACH UNTEN ZUM DUCKEN",
            },
        },
        hooks: {
            fetchError: "Bestenliste konnte nicht geladen werden - die Elfen haben Mittagspause",
            submitError: "Score konnte nicht gespeichert werden. Hast du am Kabel gewackelt?",
        }
    },
    en: {
        common: {
            score: "Score",
            loading: "Loading...",
            error: "Error",
            retry: "Try again (you unlucky soul)",
            done: "DONE",
            back: "BACK",
            pause: "PAUSE",
            continue: "RESUME",
            exit: "QUIT",
            saving: "SAVING...",
            submit: "SUBMIT",
            cancel: "CANCEL",
        },
        menu: {
            title: "Merry Games",
            grinchTitle: "Grumpy Games",
            finaleBadge: "FINALS",
            settings: "SETTINGS",
            play: "PLAY",
            info: "INFO",
            snowballTitle: "Snowball Hunt",
            snowballDesc: "Tap on gifts and stars to collect points. Avoid the coal unless you've been naughty! Use ice for a freeze or clocks for more time.",
            giftTitle: "Gift Toss",
            giftDesc: "Tap to drop gifts. Aim for the chimneys! Watch out for obstacles like planes and clouds - Santa's insurance doesn't cover that!",
            runnerTitle: "Reindeer Run",
            runnerDesc: "Run endlessly through the snowy landscape! Tap to jump, swipe down to duck. Dodge obstacles and collect points!",
            expired: "EXPIRED",
            githubHelp: "Help make this game better!",
            githubVisit: "Visit us on GitHub:",
        },
        settings: {
            title: "Settings",
            duration: "Game Duration",
            sound: "Sound Effects",
            soundOn: "On",
            soundOff: "Off",
            theme: "Appearance",
            themeClassic: "Classic Mode",
            themeGrinch: "Grinch Mode",
            min: "Min",
            sec: "Sec",
        },
        game: {
            newHighScore: "NEW HIGH SCORE!",
            yourScore: "Your Score",
            enterName: "ENTER NAME",
            finished: "DONE!",
            jokeTitle: "Christmas Joke:",
            toMenu: "TO MAIN MENU",
            noScores: "No scores yet - be the first!",
            leaderboard: "Leaderboard",
            thanks: "Thanks for your help, Santa! Without you, the kids would've gotten nothing!",
            freeze_text: "FREEZE!",
            poof: "POOF!",
            perfect: "PERFECT",
            miss: "Miss",
            playableUntil: "Playable until 01.01.2026",
            gameEnded: "Game ended",
            gameEndedTitle: "Ho ho ho... and that's a wrap!",
            gameEndedMessage: "The Santa Games are officially over! Thanks to all brave players who saved Santa's presents. The reindeer are exhausted, the elves are on vacation, and the sleigh's in the shop. Will we be back next year? Who knows... maybe if you've been good! 🎅✨",
            player: "player",
            players: "players",
            eternalGlory: "Eternal Glory awaits the Champions!",
            runner: {
                tapToJump: "TAP TO JUMP",
                swipeDown: "SWIPE DOWN TO DUCK",
            },
        },
        hooks: {
            fetchError: "Failed to load leaderboard - the elves are on lunch break",
            submitError: "Score couldn't be saved. Did you wiggle the cable?",
        }
    }
};

export const WEIHNACHTS_WITZE = {
    de: [
        "Warum hat der Schneemann keine Beine? Weil er sonst weglaufen würde, wenn er gelbe Flecken sieht!",
        "Was ist das Lieblingsessen von Rentieren? Rentier-Gulasch... oh warte, das ist ja Kannibalismus!",
        "Was sagt der Nikolaus, wenn er in den Schornstein guckt? 'Hier zieht's - und es riecht komisch!'",
        "Warum ist der Weihnachtsmann so gut gebildet? Er hat jahrelang 'Präsenz-Unterricht' gegeben!",
        "Was bekommt ein artiges Kind zu Weihnachten? Ein Tablet. Und ein unartiges? Eine Paracetamol-Tablette!",
        "Wer klopft an die Tür und ist ganz weiß? Der Schneemann - er hat vergessen zu klingeln!",
        "Wie nennt man einen alten Schneemann? Eine Pfütze mit Existenzkrise!",
        "Warum hat der Weihnachtsmann einen Sack? Weil Amazon Prime zu teuer war!",
        "Was ist rot, dick und sitzt im Wald fest? Der Weihnachtsmann nach zu viel Glühwein!",
        "Warum kommt der Weihnachtsmann durch den Schornstein? Weil die Haustür abgeschlossen war - logisch!",
        "Was macht der Weihnachtsmann nach Weihnachten? Burnout-Klinik!",
        "Warum tragen Elfen Glocken? Damit Santa sie im Dunkeln nicht überfährt!",
    ],
    en: [
        "What do you call an old snowman? A puddle with an identity crisis!",
        "Why does Santa go down the chimney? Because the front door was locked - duh!",
        "What do you get when you cross a snowman and a vampire? Frostbite and a lawsuit!",
        "What falls but never gets hurt? Snow. Unlike your Christmas expectations!",
        "What did one snowman say to the other? 'Do you smell carrots or is that just Gary again?'",
        "What does Santa use when he goes flying? A sleigh-nav, because GPS is for rookies!",
        "How do snowmen get around? On icicles - Uber doesn't go to the North Pole!",
        "What kind of music do elves like? Wrap music - and no, that's not a typo!",
        "Why is Santa so good at karate? Because he has a black belt... from Amazon!",
        "What did the gingerbread man put on his bed? Cookie sheets - he's not very creative!",
        "What does Santa do after Christmas? Checks into rehab for eggnog addiction!",
        "Why do elves wear bells? So Santa doesn't run them over in the dark!",
    ]
};

export const SPRUECHE = {
    de: [
        "Putz dir die Nase, das ist ja eklig!",
        "Das war knapper als Santa's Hosenbund!",
        "Hoppla! Zwei linke Hände heute?",
        "Oha! Bist du heute mit dem falschen Fuß aufgestanden?",
        "Hast du Tomaten auf den Augen oder bist du einfach blind?",
        "Meine Oma klickt schneller - und die ist 87!",
        "Oje, oje! Das war ja peinlich!",
        "Autsch! Das tat sogar MIR weh!",
        "Na toll! Jetzt ist's passiert!",
        "Konzentration, junger Padawan!",
        "Das kannst du besser - oder etwa nicht?",
        "Ups! Da ist wohl jemand mit den Gedanken woanders!",
    ],
    en: [
        "Watch your nose - that's disgusting!",
        "That was closer than Santa's waistband!",
        "Oops! Two left hands today?",
        "Whoa! Did you wake up on the wrong side of the bed?",
        "Are you blind or just playing 4D chess?",
        "My grandma clicks faster - and she's 87!",
        "Oh boy, oh boy! That was embarrassing!",
        "Ouch! That hurt ME too!",
        "Great job! Now look what happened!",
        "Focus, young Padawan!",
        "You can do better than that - or can you?",
        "Whoopsie! Someone's mind is elsewhere!",
    ]
};

export const PARCEL_TEXTS = {
    de: [
        "Sorry, Santa hatte keine Zeit mehr zum Einpacken!",
        "Das Rentier hat das Geschenkpapier gefressen...",
        "Nicht schön, aber der Inhalt zählt!",
        "Express-Lieferung direkt vom Nordpol!",
        "Ups, das Geschenkpapier ist ausgegangen!"
    ],
    en: [
        "Sorry, Santa didn't manage to wrap your gift!",
        "The reindeer ate the wrapping paper...",
        "It's not pretty, but it's what's inside that counts!",
        "Express delivery straight from the North Pole!",
        "Oops, ran out of wrapping paper!"
    ]
};